### ISSUE TITLE
启动成功之后，跳转页面是404，请问下如何解决

### ISSUE THREAD

**Issue by Benjiemin1997** [blackist/ar#11]
[](url)

**Comment by blackist** [comment]
很有可能是访问路径的问题，IDE 启动后默认的访问路径不对，使用如下路径：

访问地址: http://localhost:8080/ar-portal/index.action 
用户名 / 密码: black/12345678

**Comment by blackist** [comment]
建议使用 Tomcat8 规避部署问题
