### ISSUE TITLE
tomcat构建出错

### ISSUE THREAD

**Issue by liusoon** [blackist/ar#16]
![image](https://user-images.githubusercontent.com/55847789/105045752-3c229300-5aa3-11eb-8bf0-1d99360f59de.png)
在最后部署时出现这个错误是怎么回事啊

**Comment by liusoon** [comment]
我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
![image](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)

**Comment by Ezio6** [comment]
> 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> ![image](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846

> 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> ![image](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)

我也遇到这个问题了

**Comment by Ezio6** [comment]
> 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> ![image](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)

> 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> ![image](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)

是tomcat的原因吗？

**Comment by liusoon** [comment]
> > 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> > ![图像](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)
> 
> > 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> > ![图像](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)
> 
> 是tomcat的原因吗？



> > 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> > ![图像](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)
> 
> > 我尝试解决了问题，虽然项目可以部署，但是打开页面显示404
> > ![图像](https://user-images.githubusercontent.com/55847789/105139846-cdd8e180-5b31-11eb-808f-37b0c2846a03.png)
> 
> 是tomcat的原因吗？

有可能是tomcat版本问题

**Comment by blackist** [comment]
建议使用 Tomcat8.0 版本 https://github.com/blackist/ar#%E4%BD%BF%E7%94%A8idea%E8%BF%90%E8%A1%8C
