### ISSUE TITLE
老铁你这项目能跑起来啊？

### ISSUE THREAD

**Issue by einsbiao** [blackist/ar#2]

**Comment by blackist** [comment]
这个项目基于Maven构建，使用SSM框架做的，简单来说maven可以自动帮你去下载jar包，也可以把项目分模块，比如这个项目被分成common,manage,portal，manage和portal依赖common，运行时maven把common打包成jar ，被portal,manage引用，都是maven来完成的。
建议大家先学习一下Maven和SSM

**Comment by ghost** [comment]
你的sql文件我怎么没找到，求解答一下

**Comment by blackist** [comment]
> 你的sql文件我怎么没找到，求解答一下

在ar/ar-doc/sql/ar-mysql-data.sql中

![ar-issue-sql](https://user-images.githubusercontent.com/14222164/54246194-dbed6c80-456e-11e9-911e-74bfc26ac301.png)

**Comment by mmtian** [comment]
![image](https://user-images.githubusercontent.com/32121698/54677692-6a00be80-4b3e-11e9-99b4-dacf959c62e8.png)
请问这个是什么原因啊，求指教

**Comment by qiyemy** [comment]
可以跑起来 没问题

**Comment by wenchangming211** [comment]
看着不错，试用一下

**Comment by wenchangming211** [comment]
请问这个问题怎么解决？
[ERROR] Failed to execute goal on project ar-manage: Could not resolve dependencies for project com.xzit.ar:ar-manage:war:0.0.1-SNAPSHOT: Failure to find taglibs:standard:jar:1.2.3 in http://maven.oa.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of internal has elapsed or updates are forced -> [Help 1]
[ERROR]

**Comment by wenchangming211** [comment]
> 请问这个问题怎么解决？
> [ERROR] Failed to execute goal on project ar-manage: Could not resolve dependencies for project com.xzit.ar:ar-manage:war:0.0.1-SNAPSHOT: Failure to find taglibs:standard:jar:1.2.3 in http://maven.oa.com/nexus/content/groups/public/ was cached in the local repository, resolution will not be reattempted until the update interval of internal has elapsed or updates are forced -> [Help 1]
> [ERROR]

已经解决了，谢谢
