### ISSUE TITLE
路径与静态资源访问问题

### ISSUE THREAD

**Issue by T-Jose** [blackist/ar#6]
发布帖子，删除帖子会碰到路径错误导致页面404，还有其他地方也会有相似的问题；静态资源在个人中心，或者论坛内，用户头像显示不出来的问题，求教。谢谢。

**Comment by blackist** [comment]
**关于部分图片源加载不到**  是因为使用了Tomcat的虚拟路径，可在Tomcat中添加虚拟节点映射到本地的真实文件夹路径。
比如添加节点 "/ar" 映射到 "D:\cahce\ar\"，当浏览器访问http://localhost:8080/ar-portal/ar/pic/asd123.png时 回去加载 D:\cache\ar\pic\asd123.png 这个图片。

Tomcat虚拟节点相关配置可自行学习。
