### ISSUE TITLE
门户网站端登录失败

### ISSUE THREAD

**Issue by daydayupw** [blackist/ar#7]
亮亮同学好，
我门户网站在本地浏览器打开后，登录跳转到404.
但是管理段在本地浏览器打开后，登录成功。
请问是什么原因呢？应该不是数据库的问题。

**Comment by blackist** [comment]
能不能把截图或日志贴出来

**Comment by daydayupw** [comment]
门户网站登录跳出404后，如果在网址中输入首页地址，可以显示（相当于登录成功）。但是不会登录后自动跳转到首页，而是出现404.
![p03](https://user-images.githubusercontent.com/55934225/65827767-58a32680-e2c6-11e9-8c3a-9cb7892caef6.png)
![p04](https://user-images.githubusercontent.com/55934225/65827768-593bbd00-e2c6-11e9-8b88-8b2455d66cdf.png)

**Comment by blackist** [comment]
校友录项目部署到Tomcat，默认访问路径为 /ar-portal/*.action，后台也是根据 ar-* 做权限拦截的，因此你这里修改了部署路径，导致重定向和转发存在部分问题。
这也是项目的一个缺陷，你可以尝试修改项目的部署路径来修复bug。

**Comment by Cammeron-chen** [comment]
用你的来改成我的毕业设计，可以得吧

**Comment by blackist** [comment]
> 用你的来改成我的毕业设计，可以得吧

这是我说可以就可以的吗
