### ISSUE TITLE
图片资源问题

### ISSUE THREAD

**Issue by daydayupw** [blackist/ar#8]
数据库中存放的是图片的本地路径，但是工程里边并没有存储图片。而且网站的个人信息管理中上传图片的功能也不能使用。那么要使得网站的个人图片正常显示，是不是只能自己建立一个本地文件夹，存储大量图片，并且把图片的命名和数据库中的路径保持一致？？？这样有点麻烦呀，该怎么办呢？？？谢谢兄弟！

**Comment by blackist** [comment]
https://github.com/blackist/ar/issues/6#issuecomment-508104088
