### ISSUE TITLE
网页图片路径更新问题

### ISSUE THREAD

**Issue by daydayupw** [blackist/ar#9]
你好，我在数据库中把所有图片的路径都重写了，但是重启工程后，打开网页依然加载不出图片，检查网页代码，发现图片路径仍然为原始路径。网页缓存已经关闭，而且换个浏览器还是一样。请问是不是你在代码里把数据库读到的路径保存到了本地，以后工程运行时只是从本地读取的图片路径，而不会读取数据库中最新的图片路径呢？

![p01](https://user-images.githubusercontent.com/55934225/65827730-e3cfec80-e2c5-11e9-80f1-5654ae5fc1c2.png)
![p02](https://user-images.githubusercontent.com/55934225/65827731-e3cfec80-e2c5-11e9-8cd3-4518373a27fe.png)

**Comment by daydayupw** [comment]
![p05](https://user-images.githubusercontent.com/55934225/65827832-fdbdff00-e2c6-11e9-9b43-d757a176041a.png)

**Comment by blackist** [comment]
有一种可能是缓存，本项目开启了 EHCache 缓存，查询的记录会保存在本地磁盘，由于你直接操作数据库，Spring不会清理失效缓存，需手动清理或等待其过期失效。
EhCache 位置是在 ehcache.xml 中配置的。
